"use client";
import { useEffect, useState } from "react";
const content = {
 en: { nav:["Home","Solutions","Governance","Contact"], language:"العربية", title:"Rooted in principle.", emphasis:"Built for possibility.", intro:"Shariah-compliant payments infrastructure for the Gulf.", description:"Secure. Governed. Built for the UAE and MENA.", action:"Explore Maghanim", secondary:"Our principles", region:"UAE & MENA", field:"A considered approach to payments", scroll:"Discover what drives us", solutions:"Regional ambition.\nA principled foundation.", solutionsText:"The future of payments should reflect the people and businesses it serves. Maghanim brings a Gulf perspective to payment infrastructure, with Shariah compliance at its core.", rows:[["Payments infrastructure","A foundation for the way businesses move value."],["Built for the Gulf","A regional focus on the UAE and wider MENA market."],["Shariah at the core","Principles that shape the direction from the outset."]], governance:"Trust begins\nwith principle.", governanceText:"Our approach starts with a simple conviction: the foundations matter as much as the possibilities they create.", principles:[["Shariah compliance","The central commitment behind Maghanim’s approach to payments."],["Security","A guiding priority for the infrastructure we are building."],["Governance","Accountability as a foundation, from the very beginning."]], contact:"Let’s shape what comes next.", contactText:"A new way to begin is coming soon.", contactAction:"Get started", notice:"Enquiries are not open yet. Please check back soon.", footer:"Payments with principle.", menu:"Open navigation", close:"Close navigation", skip:"Skip to content" },
 ar: { nav:["الرئيسية","الحلول","الحوكمة","تواصل معنا"], language:"English", title:"راسخة في المبادئ.", emphasis:"مصممة لآفاق جديدة.", intro:"بنية تحتية للمدفوعات المتوافقة مع الشريعة في الخليج.", description:"آمنة. محكومة. صُمّمت للإمارات والشرق الأوسط وشمال أفريقيا.", action:"اكتشف مغانم", secondary:"مبادئنا", region:"الإمارات والمنطقة", field:"رؤية مدروسة للمدفوعات", scroll:"اكتشف ما يحركنا", solutions:"طموح إقليمي.\nأساس من المبادئ.", solutionsText:"ينبغي أن يعكس مستقبل المدفوعات احتياجات الأفراد والشركات. تقدم مغانم منظوراً خليجياً للبنية التحتية للمدفوعات، مع الالتزام بالشريعة في صميم رؤيتها.", rows:[["البنية التحتية للمدفوعات","أساس لحركة القيمة في عالم الأعمال."],["مصممة للخليج","تركيز إقليمي على الإمارات والشرق الأوسط وشمال أفريقيا."],["الشريعة في صميم رؤيتنا","مبادئ ترسم توجهنا منذ البداية."]], governance:"الثقة تبدأ\nبالمبادئ.", governanceText:"يبدأ نهجنا بقناعة بسيطة: الأسس لا تقل أهمية عن الآفاق التي تفتحها.", principles:[["الالتزام بالشريعة","الالتزام الأساسي الذي يقوم عليه نهج مغانم في المدفوعات."],["الأمان","أولوية توجه البنية التحتية التي نبنيها."],["الحوكمة","المساءلة أساس منذ البداية."]], contact:"لنصنع معاً ما يأتي.", contactText:"تجربة البداية الجديدة ستكون متاحة قريباً.", contactAction:"ابدأ الآن", notice:"لم تُفتح الاستفسارات بعد. يرجى العودة قريباً.", footer:"مدفوعات تقوم على المبادئ.", menu:"فتح قائمة التنقل", close:"إغلاق قائمة التنقل", skip:"انتقل إلى المحتوى" }
};
function Arrow({down=false}:{down?:boolean}) {return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true" className={down?"arrow-down":""}><path d="M5 12h14M12 5l7 7-7 7"/></svg>}
function Seal(){return <svg className="seal" viewBox="0 0 400 400" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="1"><circle cx="200" cy="200" r="174"/><circle cx="200" cy="200" r="163"/>{[0,45,90,135].map(a=><rect key={a} x="93" y="93" width="214" height="214" transform={`rotate(${a} 200 200)`}/>)}<circle cx="200" cy="200" r="115"/></g></svg>}
export default function Home(){
 const [language,setLanguage]=useState<"en"|"ar">("en"); const [menuOpen,setMenuOpen]=useState(false); const [noticeVisible,setNoticeVisible]=useState(false); const c=content[language];
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=language==="ar"?"rtl":"ltr"},[language]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setMenuOpen(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
 return <main dir={language==="ar"?"rtl":"ltr"}>
 <a className="skip-link" href="#top">{c.skip}</a><div className="opening"><div className="heritage-pattern" aria-hidden="true"/><header className="site-header wrap"><a className="brand" href="#top" aria-label="Maghanim"><img src="/wordmark.png" alt="Maghanim" width="680" height="126"/></a><nav id="primary-nav" className={`site-nav ${menuOpen?"is-open":""}`} aria-label={language==="ar"?"التنقل الرئيسي":"Primary navigation"}>{c.nav.map((label,i)=><a key={i} href={["#top","#solutions","#governance","#contact"][i]} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav><div className="header-actions"><button className="language-control" onClick={()=>{setLanguage(language==="en"?"ar":"en");setMenuOpen(false)}} lang={language==="en"?"ar":"en"}>{c.language}</button><button className={`menu-toggle ${menuOpen?"is-open":""}`} aria-label={menuOpen?c.close:c.menu} aria-controls="primary-nav" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><span/><span/></button></div></header>
 <section className="hero wrap" id="top" aria-labelledby="hero-title"><div className="hero-copy"><div className="hero-mark" aria-hidden="true">مغانم</div><h1 id="hero-title">{c.intro}</h1><p className="hero-description">{c.description}</p><div className="hero-actions"><a className="button" href="#solutions">{c.action}<Arrow/></a><a className="text-link" href="#governance">{c.secondary}<Arrow/></a></div></div><div className="coin-stage"><div className="coin-orbit"/><img className="hero-coin" src="/coin-hero.png" alt={language==="ar"?"عملة مغانم الذهبية المنقوشة":"Gold coin bearing the Maghanim Arabic engraving"} width="1000" height="1000" fetchPriority="high"/><span className="coin-caption">{c.field}</span></div></section><div className="hero-foot wrap"><span>{c.region}</span><a href="#solutions">{c.scroll}<Arrow down/></a><span className="brand-year">MAGHANIM</span></div></div>
 <section className="solutions wrap section" id="solutions" aria-labelledby="solutions-title"><div className="section-intro"><h2 id="solutions-title">{c.solutions}</h2><p>{c.solutionsText}</p></div><div className="solution-list">{c.rows.map(([title,description])=><article key={title}><h3>{title}</h3><p>{description}</p><Arrow/></article>)}</div></section>
 <section className="governance" id="governance" aria-labelledby="governance-title"><div className="governance-inner wrap section"><div className="governance-art"><Seal/><span>{language==="ar"?"مغانم":"M"}</span></div><div className="governance-copy"><h2 id="governance-title">{c.governance}</h2><p>{c.governanceText}</p><div className="principles">{c.principles.map(([title,description])=><article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></div></div></section>
 <footer id="contact" className="wrap"><div className="contact"><div><h2>{c.contact}</h2><p>{c.contactText}</p></div><div className="contact-action"><button className="button" onClick={()=>setNoticeVisible(true)}>{c.contactAction}<Arrow/></button>{noticeVisible&&<p role="status">{c.notice}</p>}</div></div><div className="footer-bottom"><a className="brand" href="#top" aria-label="Maghanim"><img src="/wordmark.png" alt="Maghanim" width="680" height="126" loading="lazy"/></a><span>{c.footer}</span><span>© {new Date().getFullYear()} Maghanim</span></div></footer></main>
}
